# Copyright 2025 AI SOC Contributors
# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

import time

from fastapi import Request, Response
from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
    generate_latest,
    CONTENT_TYPE_LATEST,
)

# ── HTTP instrumentation ────────────────────────────────────────────────────

HTTP_REQUESTS = Counter(
    "soc_http_requests_total",
    "Total HTTP requests by method, path, and status code",
    ["method", "path", "status"],
)

HTTP_LATENCY = Histogram(
    "soc_http_request_duration_seconds",
    "HTTP request duration in seconds",
    ["method", "path"],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0],
)

# ── Pipeline business metrics ───────────────────────────────────────────────

HITL_PENDING = Gauge(
    "soc_hitl_pending_reviews",
    "Number of HITL reviews currently awaiting analyst decision",
)

HITL_DECISIONS = Counter(
    "soc_hitl_decisions_total",
    "Total HITL decisions submitted",
    ["action"],
)

ALERTS_PROCESSED = Counter(
    "soc_alerts_processed_total",
    "Total alerts processed by the pipeline",
    ["outcome"],  # executed | dropped | escalated | pending
)

PIPELINE_ERRORS = Counter(
    "soc_pipeline_errors_total",
    "Pipeline stage errors",
    ["stage"],
)

PLAYBOOKS_GENERATED = Counter(
    "soc_playbooks_generated_total",
    "Playbooks generated by LLM",
    ["category"],
)

LLM_LATENCY = Histogram(
    "soc_llm_call_duration_seconds",
    "LLM completion call duration in seconds",
    buckets=[0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0],
)

# ── Middleware ──────────────────────────────────────────────────────────────

_SKIP_PATHS = {"/metrics", "/health", "/openapi.json", "/docs", "/redoc"}


async def prometheus_middleware(request: Request, call_next):
    path = request.url.path
    start = time.perf_counter()
    response = await call_next(request)
    duration = time.perf_counter() - start

    if path not in _SKIP_PATHS:
        HTTP_REQUESTS.labels(
            method=request.method,
            path=path,
            status=str(response.status_code),
        ).inc()
        HTTP_LATENCY.labels(method=request.method, path=path).observe(duration)

    return response


def metrics_endpoint() -> Response:
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)
