apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - infra/kafka-statefulset.yaml
  - infra/kafka-service.yaml
  - infra/redis-statefulset.yaml
  - infra/redis-service.yaml
  - infra/postgres-statefulset.yaml
  - infra/postgres-service.yaml
  - infra/chromadb-statefulset.yaml
  - infra/chromadb-service.yaml
  - app/api-deployment.yaml
  - app/api-service.yaml
  - app/orchestrator-deployment.yaml
  - app/wazuh-bridge-deployment.yaml
